# Generated by Django 2.2.16 on 2020-10-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='county',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='parish',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='sub_county',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='village',
        ),
    ]
