# Generated by Django 2.2.16 on 2020-09-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Group Name'),
        ),
    ]
