# Generated by Django 2.2.16 on 2020-09-08 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmer', '0002_auto_20200908_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unffe_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='credit_acces',
            field=models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=True, verbose_name='Have access to credit ?.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='experience',
            field=models.FloatField(default=1.0, verbose_name='Experience in years'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='general_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='number_of_dependants',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='production_scale',
            field=models.CharField(choices=[(None, '---please select---'), ('subsistence', 'subsistence'), ('commercial', 'commercial')], default='small', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='status',
            field=models.CharField(default='in_active', max_length=20),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='type_of_land',
            field=models.CharField(choices=[(None, '---please select---'), ('rented', 'Rented'), ('owned', 'Owned')], default='owned', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='group',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
    ]
