# Generated by Django 2.2.16 on 2020-09-29 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20200929_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='farmer', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
