# Generated by Django 2.2.16 on 2020-09-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_auto_20200908_2045'),
        ('farmer', '0003_auto_20200908_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='sector',
            field=models.ManyToManyField(related_name='farmer_sectors', to='farm.Sector'),
        ),
    ]
