# Generated by Django 2.2.16 on 2020-10-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_auto_20201017_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
