# Generated by Django 2.2.16 on 2020-10-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_auto_20201019_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='experience',
            field=models.FloatField(verbose_name='Farming Experience in years'),
        ),
    ]
