# Generated by Django 2.2.16 on 2020-09-11 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_farmerprofile_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerprofile',
            old_name='credit_acces',
            new_name='credit_access',
        ),
    ]
