# Generated by Django 2.2.16 on 2020-09-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_auto_20200911_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerprofile',
            old_name='land_owned',
            new_name='size_of_land',
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_active', 'In-Active'), ('rejected', 'Rejected')], default='in_active', max_length=20),
        ),
    ]
