# Generated by Django 2.2.16 on 2020-09-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_auto_20200911_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='status',
            field=models.CharField(choices=[(None, '--please select--'), ('active', 'Active'), ('in_active', 'In-Active'), ('rejected', 'Rejected')], default='True', max_length=20),
        ),
    ]
