# Generated by Django 2.2.16 on 2020-10-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_auto_20201020_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='credit_access',
            field=models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], verbose_name='Have access to credit ?.'),
        ),
    ]
