# Generated by Django 2.2.16 on 2020-10-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_auto_20201020_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='status',
            field=models.CharField(choices=[(None, '--please select--'), ('Active', 'Active'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
