# Generated by Django 2.2.16 on 2020-09-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_auto_20200922_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='status',
            field=models.CharField(choices=[(None, '--please select--'), ('Active', 'Active'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='in_active', max_length=20),
        ),
    ]
