# Generated by Django 2.2.16 on 2020-10-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0010_auto_20201021_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='source_of_credit',
            field=models.CharField(choices=[(None, '--please select--'), ('SACCO', 'SACCO'), ('VSLA', 'VSLA'), ('Bank', 'Bank')], max_length=25, null=True),
        ),
    ]
