# Generated by Django 2.2.16 on 2020-10-13 09:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='contacts',
        ),
        migrations.AddField(
            model_name='resource',
            name='Phone_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone number 1'),
        ),
        migrations.AddField(
            model_name='resource',
            name='Phone_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone number 2'),
        ),
    ]
