# Generated by Django 2.2.16 on 2020-09-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebooking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[(None, '--please select--'), ('credit', 'credit'), ('full_payment', 'full_payment'), ('installements', 'installements'), ('exchange', 'exchange')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='resourcebooking',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[(None, '--please select--'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobilemoney', 'mobilemoney'), ('credit_card', 'credit card'), ('others', 'Others')], max_length=25, null=True),
        ),
    ]
