# Generated by Django 2.2.16 on 2020-09-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesharing', '0002_auto_20200911_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='lon',
            new_name='longitude',
        ),
    ]
