# Generated by Django 2.2.16 on 2020-10-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesharing', '0002_auto_20201013_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='availability_date_and_time',
        ),
        migrations.AddField(
            model_name='resource',
            name='available_from',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='available_to',
            field=models.DateField(auto_now=True),
        ),
    ]
