# Generated by Django 2.2.16 on 2020-10-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesharing', '0003_auto_20201013_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
