# Generated by Django 2.2.16 on 2020-10-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesharing', '0004_resource_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='termsandconditions',
            new_name='terms_and_conditions',
        ),
    ]
