# Generated by Django 2.2.16 on 2020-10-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesharing', '0005_auto_20201013_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='longitude',
            new_name='lon',
        ),
    ]
