# Generated by Django 2.2.16 on 2020-10-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesharing', '0006_auto_20201013_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebooking',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[(None, '--please select--'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobilemoney', 'Mobile Money'), ('credit_card', 'credit card'), ('others', 'Others')], max_length=25, null=True),
        ),
    ]
