# Generated by Django 2.2.16 on 2020-10-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesharing', '0007_auto_20201014_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitude of your location', null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='lon',
            field=models.FloatField(blank=True, help_text='Longitude of your location', null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price(shs)'),
        ),
    ]
