# Generated by Django 2.2.16 on 2020-10-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='population',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
