# Generated by Django 2.2.16 on 2020-10-17 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.County'),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.District'),
        ),
        migrations.AddField(
            model_name='profile',
            name='parish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Parish'),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Region'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sub_county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.SubCounty'),
        ),
        migrations.AddField(
            model_name='profile',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Village'),
        ),
    ]
