# Generated by Django 2.2.16 on 2020-09-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
