# Generated by Django 2.2.16 on 2020-10-01 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_district_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='population',
        ),
    ]
