# Generated by Django 2.2.16 on 2020-10-17 18:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20201017_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number 2'),
        ),
    ]
