# Generated by Django 2.2.16 on 2020-09-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200918_1346'),
        ('common', '0004_auto_20200918_1110'),
    ]

    operations = [
    ]
