# Generated by Django 2.2.16 on 2020-10-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_enterpriseselection_user'),
        ('common', '0001_initial'),
        ('unffeagents', '0002_caller_callrsponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='upload',
        ),
        migrations.AddField(
            model_name='notice',
            name='county',
            field=models.ManyToManyField(related_name='notice_counties', to='common.County'),
        ),
        migrations.AddField(
            model_name='notice',
            name='district',
            field=models.ManyToManyField(related_name='notice_districts', to='common.District'),
        ),
        migrations.AddField(
            model_name='notice',
            name='parish',
            field=models.ManyToManyField(related_name='notice_parishes', to='common.Parish'),
        ),
        migrations.AddField(
            model_name='notice',
            name='sector',
            field=models.ManyToManyField(related_name='notice_sectors', to='farm.Sector'),
        ),
        migrations.AddField(
            model_name='notice',
            name='sub_county',
            field=models.ManyToManyField(related_name='notice_sub_counties', to='common.SubCounty'),
        ),
        migrations.AddField(
            model_name='notice',
            name='village',
            field=models.ManyToManyField(related_name='notice_villages', to='common.Village'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_title',
            field=models.CharField(max_length=200),
        ),
    ]
