# Generated by Django 2.2.16 on 2020-10-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unffeagents', '0003_auto_20201016_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='county',
            field=models.ManyToManyField(blank=True, related_name='notice_counties', to='common.County'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='district',
            field=models.ManyToManyField(blank=True, related_name='notice_districts', to='common.District'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='sub_county',
            field=models.ManyToManyField(blank=True, related_name='notice_sub_counties', to='common.SubCounty'),
        ),
    ]
