# Generated by Django 2.2.16 on 2020-10-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unffeagents', '0004_auto_20201017_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='parish',
            field=models.ManyToManyField(blank=True, related_name='notice_parishes', to='common.Parish'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='sector',
            field=models.ManyToManyField(blank=True, related_name='notice_sectors', to='farm.Sector'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='village',
            field=models.ManyToManyField(blank=True, related_name='notice_villages', to='common.Village'),
        ),
    ]
