# Generated by Django 2.2.16 on 2020-10-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unffeagents', '0005_auto_20201019_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
