# Generated by Django 2.2.16 on 2020-10-14 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('farm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farm.Enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[(None, '---please select---'), ('female', 'Female'), ('male', 'Male')], max_length=15)),
                ('marital_status', models.CharField(choices=[(None, '--please select--'), ('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=15)),
                ('seller_type', models.CharField(choices=[(None, '--please select--'), ('wholeseller', 'wholeseller'), ('retail', 'retail')], max_length=15)),
                ('business_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('business_location', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[(None, '--please select--'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='in_active', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller_unffe_agent', to=settings.AUTH_USER_MODEL)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.County')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.District')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Enterprise')),
                ('major_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openmarket.Product')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Parish')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Region')),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.SubCounty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Village')),
            ],
            options={
                'ordering': ('seller_type',),
            },
        ),
        migrations.CreateModel(
            name='SoilScience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('operation_mode', models.CharField(max_length=50, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(None, '--please select--'), ('Active', 'Active'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='True', max_length=20)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin', models.CharField(max_length=50, null=True, verbose_name='National Identity Number (NIN)')),
                ('service_provider_location', models.CharField(max_length=50, null=True)),
                ('list_of_services_if_more_than_one', models.CharField(blank=True, max_length=50)),
                ('service_type', models.CharField(max_length=50, null=True)),
                ('phone_1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone number 1')),
                ('phone_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number 2')),
                ('is_the_service_available', models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], null=True)),
                ('service_location', models.CharField(max_length=100, null=True)),
                ('is_the_service_at_a_fee', models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], null=True)),
                ('category', models.CharField(choices=[(None, '--please select--'), ('storage', 'Storage'), ('transport', 'Transport'), ('value addition', 'Value Addition'), ('sorting and graining', 'Sorting and Graining'), ('Medical Services', 'Medical Services'), ('machinery', 'Machinery'), ('land', 'Land'), ('others', 'Others')], max_length=50, null=True)),
                ('status', models.CharField(choices=[(None, '--please select--'), ('Active', 'Active'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unffe_agent_service_provider', to=settings.AUTH_USER_MODEL)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.County')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.District')),
                ('parish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Parish')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Region')),
                ('sub_county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.SubCounty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceprovider', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Village')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[(None, '--please select--'), ('storage', 'Storage'), ('transport', 'Transport'), ('value addition', 'Value Addition'), ('sorting and graining', 'Sorting and Graining'), ('Medical Services', 'Medical Services'), ('machinery', 'Machinery'), ('land', 'Land'), ('others', 'Others')], max_length=50, null=True)),
                ('service_name', models.CharField(max_length=200, null=True)),
                ('service_type', models.CharField(max_length=50, null=True)),
                ('size', models.FloatField(blank=True, max_length=50, null=True)),
                ('terms_and_conditions', models.BooleanField(default=True)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('availability_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('available_services', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('rent', models.CharField(blank=True, max_length=25, null=True)),
                ('name_of_storage_center', models.CharField(blank=True, max_length=50, null=True)),
                ('location_of_storage_center', models.CharField(blank=True, max_length=50, null=True)),
                ('certification_status', models.BooleanField(blank=True, choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], null=True, verbose_name='Is the Service Certified')),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_capacity', models.FloatField(blank=True, help_text='capacity of your vehicle in tonnes', max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, help_text='Latitude of your industry location', null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(blank=True, help_text='Longitude of your industry location', null=True, verbose_name='Longitude')),
                ('others', models.CharField(blank=True, max_length=100, null=True, verbose_name='Please state the category if its not among the above')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(max_length=50, null=True)),
                ('price_offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_option', models.CharField(max_length=50)),
                ('payment_options', models.CharField(choices=[(None, '--please select--'), ('credit', 'credit'), ('full_payment', 'full_payment'), ('installements', 'installements'), ('exchange', 'exchange')], max_length=50, null=True)),
                ('payment_mode', models.CharField(choices=[(None, '--please select--'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobilemoney', 'Mobile Money'), ('credit_card', 'credit card'), ('others', 'Others')], max_length=50, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openmarket.Seller')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openmarket.Product')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50, null=True)),
                ('destination', models.CharField(max_length=50, null=True)),
                ('quantity', models.FloatField(max_length=50, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[(None, '--please select--'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobilemoney', 'Mobile Money'), ('credit_card', 'credit card'), ('others', 'Others')], max_length=50, null=True)),
                ('contact_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openmarket.ContactDetails')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openmarket.ServiceProvider')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openmarket.Product')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BuyerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=50)),
                ('quantity', models.FloatField(max_length=50, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_options', models.CharField(max_length=50)),
                ('payment_options', models.CharField(choices=[(None, '--please select--'), ('credit', 'credit'), ('full_payment', 'full_payment'), ('installements', 'installements'), ('exchange', 'exchange')], max_length=50, null=True)),
                ('payment_mode', models.CharField(choices=[(None, '--please select--'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobilemoney', 'Mobile Money'), ('credit_card', 'credit card'), ('others', 'Others')], max_length=50, null=True)),
                ('any_other_comment', models.TextField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openmarket.Buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openmarket.Product')),
            ],
        ),
    ]
