# Generated by Django 2.2.16 on 2020-09-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_type',
            field=models.CharField(choices=[(None, '--please select--'), ('wholeseller', 'wholeseller'), ('retail', 'retail')], max_length=15),
        ),
    ]
