# Generated by Django 2.2.16 on 2020-09-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerpost',
            old_name='Any_other_comment',
            new_name='any_other_comment',
        ),
        migrations.RenameField(
            model_name='medical',
            old_name='Time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='soilscience',
            old_name='Time',
            new_name='time',
        ),
    ]
