# Generated by Django 2.2.16 on 2020-09-22 15:11

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('openmarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='location',
            new_name='service_provider_location',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.County'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.District'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='is_the_service_at_a_fee',
            field=models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='is_the_service_available',
            field=models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='nin',
            field=models.CharField(max_length=50, null=True, verbose_name='National Identity Number (NIN)'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='parish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Parish'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='phone_1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone number 1'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='phone_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number 2'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Region'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='sub_county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.SubCounty'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Village'),
        ),
    ]
