# Generated by Django 2.2.16 on 2020-09-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0002_auto_20200922_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[(None, '--please select--'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='in_active', max_length=20),
        ),
    ]
