# Generated by Django 2.2.16 on 2020-10-23 14:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0003_auto_20201016_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='county',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='district',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='parish',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='region',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='sub_county',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='village',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[(None, '--please select--'), ('storage', 'Storage'), ('transport', 'Transport'), ('value addition', 'Value Addition'), ('sorting and graining', 'Sorting and Graining'), ('Veterinary Services', 'Veterinary Services'), ('Agro-input providers', 'Agro-input providers'), ('machinery', 'Machinery'), ('land', 'Land'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='driver_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='service',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='category',
            field=models.CharField(choices=[(None, '--please select--'), ('storage', 'Storage'), ('transport', 'Transport'), ('value addition', 'Value Addition'), ('sorting and graining', 'Sorting and Graining'), ('Veterinary Services', 'Veterinary Services'), ('Agro-input providers', 'Agro-input providers'), ('machinery', 'Machinery'), ('land', 'Land'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
