# Generated by Django 2.2.16 on 2020-09-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0003_auto_20200923_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='category',
            field=models.CharField(choices=[(None, '--please select--'), ('storage', 'Storage'), ('transport', 'Transport'), ('packaging', 'Packaging'), ('sorting and graining', 'Sorting and Graining'), ('Medical Services', 'Medical Services'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, null=True)),
                ('service_type', models.CharField(max_length=50, null=True)),
                ('size', models.FloatField(max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('service_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openmarket.ServiceProvider')),
            ],
        ),
    ]
