# Generated by Django 2.2.16 on 2020-09-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0003_auto_20200911_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
    ]
