# Generated by Django 2.2.16 on 2020-10-21 06:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0003_auto_20201016_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='driver_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='service',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
