# Generated by Django 2.2.16 on 2020-10-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0004_auto_20201021_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='county',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='district',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='parish',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='region',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='sub_county',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='village',
        ),
    ]
