# Generated by Django 2.2.16 on 2020-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0004_auto_20200911_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerpost',
            name='payment_mode',
            field=models.CharField(choices=[(None, '--please select--'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobilemoney', 'mobilemoney'), ('credit_card', 'credit card'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyerpost',
            name='payment_options',
            field=models.CharField(choices=[(None, '--please select--'), ('credit', 'credit'), ('full_payment', 'full_payment'), ('installements', 'installements'), ('exchange', 'exchange')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='payment_mode',
            field=models.CharField(choices=[(None, '--please select--'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobilemoney', 'mobilemoney'), ('credit_card', 'credit card'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpost',
            name='payment_mode',
            field=models.CharField(choices=[(None, '--please select--'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobilemoney', 'mobilemoney'), ('credit_card', 'credit card'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpost',
            name='payment_options',
            field=models.CharField(choices=[(None, '--please select--'), ('credit', 'credit'), ('full_payment', 'full_payment'), ('installements', 'installements'), ('exchange', 'exchange')], max_length=50, null=True),
        ),
    ]
