# Generated by Django 2.2.16 on 2020-09-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0004_auto_20200924_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='list_of_service',
            new_name='list_of_services_if_more_than_one',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[(None, '--please select--'), ('storage', 'Storage'), ('transport', 'Transport'), ('packaging', 'Packaging'), ('sorting and graining', 'Sorting and Graining'), ('Medical Services', 'Medical Services'), ('machinery', 'Machinery'), ('land', 'Land'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='category',
            field=models.CharField(choices=[(None, '--please select--'), ('storage', 'Storage'), ('transport', 'Transport'), ('packaging', 'Packaging'), ('sorting and graining', 'Sorting and Graining'), ('Medical Services', 'Medical Services'), ('machinery', 'Machinery'), ('land', 'Land'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
