# Generated by Django 2.2.16 on 2020-09-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0005_auto_20200911_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerpost',
            old_name='Product',
            new_name='product',
        ),
    ]
