# Generated by Django 2.2.16 on 2020-10-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0005_auto_20201021_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[(None, '--please select--'), ('storage', 'Storage'), ('transport', 'Transport'), ('value addition', 'Value Addition'), ('sorting and graining', 'Sorting and Graining'), ('Veterinary Services', 'Veterinary Services'), ('Agro-input providers', 'Agro-input providers'), ('machinery', 'Machinery'), ('land', 'Land'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='category',
            field=models.CharField(choices=[(None, '--please select--'), ('storage', 'Storage'), ('transport', 'Transport'), ('value addition', 'Value Addition'), ('sorting and graining', 'Sorting and Graining'), ('Veterinary Services', 'Veterinary Services'), ('Agro-input providers', 'Agro-input providers'), ('machinery', 'Machinery'), ('land', 'Land'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
