# Generated by Django 2.2.16 on 2020-09-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0005_auto_20200924_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='availability_date',
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='availability_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
