# Generated by Django 2.2.16 on 2020-10-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0006_auto_20201025_0646'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='serviceprovider',
        #     name='county',
        # ),
        # migrations.RemoveField(
        #     model_name='serviceprovider',
        #     name='district',
        # ),
        # migrations.RemoveField(
        #     model_name='serviceprovider',
        #     name='parish',
        # ),
        # migrations.RemoveField(
        #     model_name='serviceprovider',
        #     name='region',
        # ),
        # migrations.RemoveField(
        #     model_name='serviceprovider',
        #     name='sub_county',
        # ),
        # migrations.RemoveField(
        #     model_name='serviceprovider',
        #     name='village',
        # ),
    ]
