# Generated by Django 2.2.16 on 2020-09-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0006_auto_20200911_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactdetails',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='logistics',
            old_name='Time',
            new_name='time',
        ),
    ]
