# Generated by Django 2.2.16 on 2020-09-28 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openmarket', '0006_auto_20200925_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='terms_and_conditions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unffe_agent_service_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='status',
            field=models.CharField(choices=[(None, '--please select--'), ('Active', 'Active'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='in_active', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[(None, '--please select--'), ('storage', 'Storage'), ('transport', 'Transport'), ('value addition', 'Value Addition'), ('sorting and graining', 'Sorting and Graining'), ('Medical Services', 'Medical Services'), ('machinery', 'Machinery'), ('land', 'Land'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='category',
            field=models.CharField(choices=[(None, '--please select--'), ('storage', 'Storage'), ('transport', 'Transport'), ('value addition', 'Value Addition'), ('sorting and graining', 'Sorting and Graining'), ('Medical Services', 'Medical Services'), ('machinery', 'Machinery'), ('land', 'Land'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
