# Generated by Django 2.2.16 on 2020-09-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0007_auto_20200911_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='inventory_status',
            field=models.CharField(choices=[(None, '--please select--'), ('availabe', 'Available'), ('not_available', 'Not Available')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_active', 'In-Active'), ('rejected', 'Rejected')], default='True', max_length=20),
        ),
    ]
