# Generated by Django 2.2.16 on 2020-09-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0007_auto_20200928_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='availability_date',
            field=models.DateTimeField(max_length=8, null=True),
        ),
    ]
