# Generated by Django 2.2.16 on 2020-09-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0008_auto_20200929_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='availability_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
