# Generated by Django 2.2.16 on 2020-09-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0009_auto_20200929_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='availability_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
