# Generated by Django 2.2.16 on 2020-09-21 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openmarket', '0010_auto_20200911_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller_unffe_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[(None, '--please select--'), ('active', 'Active'), ('in_active', 'In-Active'), ('rejected', 'Rejected')], default='in_active', max_length=20),
        ),
    ]
