# Generated by Django 2.2.16 on 2020-09-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0010_auto_20200929_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRegistration',
        ),
    ]
