# Generated by Django 2.2.16 on 2020-09-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0011_delete_serviceregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='status',
            field=models.CharField(choices=[(None, '--please select--'), ('Active', 'Active'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
