# Generated by Django 2.2.16 on 2020-09-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0012_auto_20200921_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Enterprise'),
        ),
        migrations.RemoveField(
            model_name='seller',
            name='major_products',
        ),
        migrations.AddField(
            model_name='seller',
            name='major_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openmarket.Product'),
        ),
    ]
