# Generated by Django 2.2.16 on 2020-10-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0012_auto_20200930_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_provider',
            new_name='user',
        ),
    ]
