# Generated by Django 2.2.16 on 2020-10-12 09:45

from django.db import migrations, models
import django.db.models .deletion

class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0014_auto_20201001_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='inventory_status',
            field=models.CharField(choices=[(None, '--please select--'), ('pest', 'Pest'), ('disease', 'Disease'), ('general_query', 'General Query')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='storage',
            name='inventory_status',
            field=models.CharField(choices=[(None, '--please select--'), ('pest', 'Pest'), ('disease', 'Disease'), ('general_query', 'General Query')], default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='storage',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openmarket.Service'),
        ),
    ]
