# Generated by Django 2.2.16 on 2020-09-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0014_auto_20200921_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='major_products',
            field=models.CharField(max_length=15),
        ),
    ]
