# Generated by Django 2.2.16 on 2020-10-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0015_auto_20201012_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='inventory_status',
            field=models.CharField(choices=[(None, '--please select--'), ('availabe', 'Available'), ('not_available', 'Not Available')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='storage',
            name='inventory_status',
            field=models.CharField(choices=[(None, '--please select--'), ('availabe', 'Available'), ('not_available', 'Not Available')], default=True, max_length=20),
        ),
    ]
