# Generated by Django 2.2.16 on 2020-09-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0015_auto_20200921_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='enterprise',
            field=models.CharField(max_length=15),
        ),
    ]
