# Generated by Django 2.2.16 on 2020-10-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0016_auto_20201012_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={},
        ),
        migrations.RemoveField(
            model_name='storage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='name',
        ),
        migrations.AddField(
            model_name='logistics',
            name='location_of_storage_center',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logistics',
            name='name_of_storage_center',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
