# Generated by Django 2.2.16 on 2020-10-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0017_auto_20201012_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistics',
            name='description',
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='image',
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='inventory_status',
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='location_of_storage_center',
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='name_of_storage_center',
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='status',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='service',
            name='location_of_storage_center',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_of_storage_center',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='rent',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
