# Generated by Django 2.2.16 on 2020-10-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0018_auto_20201012_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='certification_status',
            field=models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
