# Generated by Django 2.2.16 on 2020-10-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0019_service_certification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitude of your industry location', null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='service',
            name='lon',
            field=models.FloatField(blank=True, help_text='Longitude of your industry location', null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
