# Generated by Django 2.2.16 on 2020-10-13 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0018_auto_20201009_0625'),
        ('openmarket', '0020_auto_20201013_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='farm.Enterprise'),
        ),
    ]
