# Generated by Django 2.2.16 on 2020-10-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0021_service_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vehicle_capacity',
            field=models.FloatField(help_text='capacity of your vehicle in tonnes', max_length=50, null=True),
        ),
    ]
