# Generated by Django 2.2.16 on 2020-10-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0022_service_vehicle_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='others',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Please state the category if its not among the above'),
        ),
        migrations.AlterField(
            model_name='service',
            name='certification_status',
            field=models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], null=True, verbose_name='Is the Service Certified'),
        ),
        migrations.AlterField(
            model_name='service',
            name='enterprise',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
