# Generated by Django 2.2.16 on 2020-10-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmarket', '0024_auto_20201013_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packaging',
            name='product',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='storage',
        ),
        # migrations.RemoveField(
        #     model_name='service',
        #     name='inventory_status',
        # ),
        # migrations.RemoveField(
        #     model_name='service',
        #     name='status',
        # ),
        migrations.AlterField(
            model_name='buyerpost',
            name='payment_mode',
            field=models.CharField(choices=[(None, '--please select--'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobilemoney', 'Mobile Money'), ('credit_card', 'credit card'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='payment_mode',
            field=models.CharField(choices=[(None, '--please select--'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobilemoney', 'Mobile Money'), ('credit_card', 'credit card'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpost',
            name='payment_mode',
            field=models.CharField(choices=[(None, '--please select--'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobilemoney', 'Mobile Money'), ('credit_card', 'credit card'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Medical',
        ),
        migrations.DeleteModel(
            name='Packaging',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
