# Generated by Django 3.0.4 on 2020-04-11 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('flat', 'Flat'), ('apartment', 'Apartment'), ('boys quarter', 'Boys Quarter')], max_length=20, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('plotNo', models.CharField(max_length=200, null=True)),
                ('rooms', models.IntegerField(null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(max_length=10, null=True)),
                ('status', models.FloatField(choices=[('vacant', 'Vacant'), ('booked', 'Booked'), ('occupied', 'Occupied')], null=True)),
                ('approval', models.CharField(choices=[('approved', 'Approved'), ('unapproved', 'Unapproved')], max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landlord.Owner'),
        ),
    ]
