# Generated by Django 3.0.4 on 2020-04-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0002_auto_20200411_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images'),
        ),
    ]
