# Generated by Django 3.0.4 on 2020-04-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0006_auto_20200417_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('booked', 'Booked'), ('occupied', 'Occupied')], default='vacant', max_length=20, null=True),
        ),
    ]
