# Generated by Django 2.2.16 on 2020-10-14 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50, verbose_name='Enterprise Name')),
                ('enterprise_type', models.CharField(max_length=200, null=True)),
                ('animal_seed_density', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of animals/seedling per enterprise in a particular period of time.')),
                ('capital_invested', models.DecimalField(decimal_places=2, max_digits=1000, null=True)),
                ('return_on_investment', models.DecimalField(decimal_places=2, max_digits=1000, null=True, verbose_name='Expected Return on Investment')),
                ('from_period', models.DateField(null=True)),
                ('to_period', models.DateField(null=True)),
                ('land_occupied', models.FloatField(null=True)),
                ('start_date', models.DateField(null=True, verbose_name='Farm Start Date')),
                ('close_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('status', models.CharField(choices=[(None, '--please select--'), ('open', 'Open'), ('closed', 'Closed')], default='active', max_length=20, verbose_name='Enterprise Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnterpriseSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_piece_of_land', models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you own a piece of land or you intend to use rented land')),
                ('what_is_your_inspiration_for_considering_in_farming', models.TextField(blank=True, null=True)),
                ('involved_in_anyother_farming_activity', models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=True, verbose_name='Have  you been involved in other farming sectors')),
                ('scale', models.CharField(max_length=100, null=True)),
                ('sector', models.CharField(max_length=100, null=True)),
                ('full_time_devotion', models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you want to devote full-time effort to the farm or would you prefer farming to be a part-time activity?')),
                ('time_allocated_to_farming', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('farm_name', models.CharField(max_length=100)),
                ('lat', models.FloatField(blank=True, help_text='Latitude of your location', null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(blank=True, help_text='Longitude of your location', null=True, verbose_name='Longitude')),
                ('start_date', models.DateField()),
                ('close_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('status', models.CharField(choices=[(None, '--please select--'), ('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20, verbose_name='Farm Status')),
                ('general_remarks', models.TextField(blank=True, null=True)),
                ('availability_of_services', models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=True, verbose_name='Have access to Services ?.')),
                ('availability_of_water', models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=True, verbose_name='Does a the farm have a water source ?.')),
                ('land_occupied', models.FloatField(null=True, verbose_name='Amount of land occupied(acres)')),
                ('available_land', models.FloatField(blank=True, null=True, verbose_name='Size of land Available')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[(None, '--please select--'), ('small', 'Small'), ('large', 'Large')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PestAndDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('query_category', models.CharField(choices=[(None, '--please select--'), ('pest', 'Pest'), ('disease', 'Disease'), ('general_query', 'General Query')], max_length=25, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_discovered', models.DateField()),
                ('action_taken', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('reporting_date', models.DateField(auto_now=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='farm_pests_and_diseases', to='farm.Farm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('transaction_type', models.CharField(choices=[(None, '--please select--'), ('income', 'Income'), ('expense', 'expense')], max_length=100)),
                ('spent_on', models.CharField(max_length=200, verbose_name='Payment for')),
                ('transaction_to', models.CharField(max_length=100, verbose_name='Payment To/From')),
                ('amount', models.FloatField(verbose_name='Amount paid')),
                ('quantity', models.FloatField()),
                ('means_of_payment', models.CharField(choices=[(None, '--please select--'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobilemoney', 'Mobile Money'), ('credit_card', 'credit card'), ('others', 'Others')], max_length=20)),
                ('transaction_date', models.DateField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='farm_financial_record', to='farm.Enterprise')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=200, verbose_name='Activity')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('taken_by', models.CharField(max_length=100, null=True, verbose_name='Taken by')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone number')),
                ('next_activity_date', models.DateField(blank=True, null=True)),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='farm_records', to='farm.Enterprise')),
                ('record_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='farm.RecordType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmProduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('quantity', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('production_date', models.DateField()),
                ('taken_by', models.CharField(blank=True, max_length=100, null=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='farm_produces', to='farm.Enterprise')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='farm.Produce')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='facilities', to='farm.Farm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
