# Generated by Django 2.2.16 on 2020-10-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='farmer.FarmerProfile'),
        ),
        migrations.AddField(
            model_name='enterprisetype',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Sector'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprises', to='farm.Farm'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Sector'),
        ),
    ]
