# Generated by Django 2.2.16 on 2020-09-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='farm', to='farmer.FarmerProfile'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Sector'),
        ),
    ]
