# Generated by Django 2.2.16 on 2020-09-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_auto_20200908_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='lon',
            new_name='longitude',
        ),
    ]
