# Generated by Django 2.2.16 on 2020-09-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_auto_20200922_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to='farmer.FarmerProfile'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='status',
            field=models.CharField(choices=[(None, '--please select--'), ('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20, verbose_name='Farm Status'),
        ),
    ]
