# Generated by Django 2.2.16 on 2020-10-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_auto_20201014_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseselection',
            name='scale',
            field=models.BooleanField(choices=[(None, '--please select--'), ('Large', 'large'), ('small', 'small')], default=True, verbose_name='If yes, at what scale do you do farming?'),
        ),
    ]
