# Generated by Django 2.2.16 on 2020-09-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_auto_20200929_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='animal_seed_density',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='expected_profit',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='initial_capital',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='animal_seed_density',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of animals/seedling per enterprise in a particular period of time.'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='expected_profit',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='land_occupied',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='availability_of_services',
            field=models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=True, verbose_name='Have access to Services ?.'),
        ),
        migrations.AddField(
            model_name='farm',
            name='availability_of_water',
            field=models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=True, verbose_name='Does a the farm have a water source ?.'),
        ),
        migrations.AddField(
            model_name='farm',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='land_occupied',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of your location', null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of your location', null=True, verbose_name='Longitude'),
        ),
    ]
