# Generated by Django 2.2.16 on 2020-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_auto_20200911_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='means_of_payment',
            field=models.CharField(choices=[(None, '--please select--'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobilemoney', 'mobilemoney'), ('credit_card', 'credit card'), ('others', 'Others')], max_length=20),
        ),
    ]
