# Generated by Django 2.2.16 on 2020-09-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_auto_20200929_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='farm',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farm.Sector'),
            preserve_default=False,
        ),
    ]
