# Generated by Django 2.2.16 on 2020-10-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_auto_20201014_1338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PestAndDisease',
            new_name='Query',
        ),
    ]
