# Generated by Django 2.2.16 on 2020-10-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_auto_20201014_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseselection',
            name='capital',
            field=models.FloatField(null=True, verbose_name='How much capital do you have to start farming?'),
        ),
        migrations.AddField(
            model_name='enterpriseselection',
            name='interested_sector',
            field=models.CharField(max_length=100, null=True, verbose_name='What Sector of farming are you interested in'),
        ),
    ]
