# Generated by Django 2.2.16 on 2020-10-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_auto_20201015_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseselection',
            name='interested_sector',
            field=models.CharField(choices=[(None, '--please select--'), ('Animal Farming', 'Animal Farming'), ('Fisheries', 'Fisheries'), ('Crop Farming', 'Crop Farming')], max_length=100, null=True, verbose_name='What Sector of farming are you interested in'),
        ),
    ]
