# Generated by Django 2.2.16 on 2020-09-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_auto_20200929_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='land_occupied',
            field=models.FloatField(null=True, verbose_name='Amount of land occupied(acres)'),
        ),
    ]
