# Generated by Django 2.2.16 on 2020-10-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_auto_20201015_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseselection',
            name='time_allocated_to_farming',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
