# Generated by Django 2.2.16 on 2020-09-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_auto_20200929_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='sector',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Farm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='available_land',
            field=models.FloatField(blank=True, null=True, verbose_name='Size of land Available'),
        ),
    ]
