# Generated by Django 2.2.16 on 2020-10-02 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_auto_20200930_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Farm'),
        ),
    ]
