# Generated by Django 2.2.16 on 2020-10-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_auto_20201002_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='sector',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Sector'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='status',
            field=models.CharField(choices=[(None, '--please select--'), ('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20, verbose_name='Enterprise Status'),
        ),
    ]
