# Generated by Django 2.2.16 on 2020-10-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_enterpriseselection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseselection',
            name='rented_land',
            field=models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you intend to use rented land?'),
        ),
        migrations.AlterField(
            model_name='enterpriseselection',
            name='involved_in_anyother_farming_activity',
            field=models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=True, verbose_name='Have  you been or are you involved in other farming sectors'),
        ),
    ]
