# Generated by Django 2.2.16 on 2020-10-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_auto_20201002_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='expected_profit',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
    ]
