# Generated by Django 2.2.16 on 2020-10-20 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_profile_phone_2'),
        ('farm', '0009_auto_20201016_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseselection',
            name='sector',
        ),
        migrations.AddField(
            model_name='enterpriseselection',
            name='land_location',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='common.District'),
        ),
        migrations.AddField(
            model_name='enterpriseselection',
            name='land_size',
            field=models.FloatField(default=False, verbose_name='What is the size of the land in acres'),
        ),
        migrations.AddField(
            model_name='enterpriseselection',
            name='level_of_education',
            field=models.CharField(choices=[(None, '---please select---'), ('primary school', 'Primary School'), ('olevel', 'Olevel'), ('Alevel', 'Alevel'), ('College', 'College'), ('University', 'University'), ('Never gone to school', 'Never gone to school')], default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='enterpriseselection',
            name='monthly_income',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='enterpriseselection',
            name='profession',
            field=models.CharField(choices=[(None, '---please select---'), ('Agriculture related', 'Agriculture related'), ('Non-agriculture related', 'Non-agriculture related')], default=False, max_length=200, verbose_name='What is your current proffession?'),
        ),
        migrations.AddField(
            model_name='enterpriseselection',
            name='region',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='common.Region'),
        ),
        migrations.AlterField(
            model_name='enterpriseselection',
            name='capital',
            field=models.FloatField(default=True, verbose_name='How much money would you be willing to invest in farming?'),
        ),
        migrations.AlterField(
            model_name='enterpriseselection',
            name='full_time_devotion',
            field=models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you want to devote full-time effort to the farm?'),
        ),
        migrations.AlterField(
            model_name='enterpriseselection',
            name='interested_sector',
            field=models.CharField(choices=[(None, '--please select--'), ('Animal Farming', 'Animal Farming'), ('Poultry Farming', 'Poultry Farming'), ('Fisheries', 'Fisheries'), ('Crop Farming', 'Crop Farming'), ('Agro Forestry', 'Agro Forestry')], max_length=100, null=True, verbose_name='What Sector of farming are you interested in'),
        ),
        migrations.AlterField(
            model_name='enterpriseselection',
            name='involved_in_anyother_farming_activity',
            field=models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=True, verbose_name='Have  you ever been involved in any farming activities'),
        ),
        migrations.AlterField(
            model_name='enterpriseselection',
            name='own_piece_of_land',
            field=models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=False, verbose_name='Do you own or have access to a piece of land to use for your farming activities'),
        ),
        migrations.AlterField(
            model_name='enterpriseselection',
            name='scale',
            field=models.CharField(choices=[(None, '--please select--'), ('Large', 'large'), ('small', 'small')], max_length=100, verbose_name='At what scale would you like to do farming?'),
        ),
    ]
