# Generated by Django 2.2.16 on 2020-10-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_auto_20201020_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseselection',
            name='scale',
            field=models.CharField(choices=[(None, '--please select--'), ('Large', 'large'), ('small', 'small')], max_length=100, null=True, verbose_name='At what scale would you like to do farming?'),
        ),
    ]
