# Generated by Django 2.2.16 on 2020-10-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_auto_20201020_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_type',
            field=models.CharField(choices=[(None, '--please select--'), ('extentional_reports', 'Extentional Report'), ('others', 'Others')], max_length=25, null=True),
        ),
    ]
