# Generated by Django 2.2.16 on 2020-10-22 14:57

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_auto_20201020_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecological_Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecological_zone_name', models.CharField(max_length=100, null=True)),
                ('list_of_crops_per_ecological_zone', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
            ],
        ),
        migrations.AlterField(
            model_name='enterpriseselection',
            name='monthly_income',
            field=models.CharField(choices=[(None, '--please select--'), ('Below 500,000ugx', 'Below 500,000ugx'), ('500,000-2,000,000', '500,000-2,000,000'), ('Above 2,000,000', 'Above 2,000,000')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseselection',
            name='scale',
            field=models.CharField(choices=[(None, '--please select--'), ('Subsistence Production', 'Subsistence Production'), ('small Commercial Production', 'small Commercial Production'), ('large Commercial Production', 'large Commercial Production')], max_length=100, null=True, verbose_name='At what scale would you like to do farming?'),
        ),
    ]
