# Generated by Django 2.2.16 on 2020-10-23 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20201023_1132'),
        ('farm', '0011_auto_20201020_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_type',
            field=models.CharField(choices=[(None, '--please select--'), ('extentional_reports', 'Extentional Report'), ('others', 'Others')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseselection',
            name='monthly_income',
            field=models.CharField(choices=[(None, '--please select--'), ('Below 500,000ugx', 'Below 500,000ugx'), ('500,000-2,000,000', '500,000-2,000,000'), ('Above 2,000,000', 'Above 2,000,000')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseselection',
            name='scale',
            field=models.CharField(choices=[(None, '--please select--'), ('Subsistence Production', 'Subsistence Production'), ('small Commercial Production', 'small Commercial Production'), ('large Commercial Production', 'large Commercial Production')], max_length=100, null=True, verbose_name='At what scale would you like to do farming?'),
        ),
        migrations.CreateModel(
            name='Ecological_Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecological_zone_name', models.CharField(max_length=100, null=True)),
                ('zone', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='common.Region')),
            ],
        ),
    ]
