# Generated by Django 2.2.16 on 2020-10-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_auto_20201006_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='name',
            new_name='farm_name',
        ),
    ]
