# Generated by Django 2.2.16 on 2020-10-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_auto_20201006_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='farmer.FarmerProfile'),
        ),
    ]
