# Generated by Django 2.2.16 on 2020-10-25 06:46

from django.db import migrations, models
import django.db.models.deletion
import django_postgres_extensions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20201023_1132'),
        ('farm', '0012_auto_20201023_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecological_Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecological_zone_name', models.CharField(max_length=100, null=True)),
                ('list_of_crops_per_ecological_zone', django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None)),
                ('zone', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='common.Region')),
            ],
        ),
    ]
