# Generated by Django 2.2.16 on 2020-10-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_auto_20201023_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='source',
            field=models.CharField(max_length=200, null=True, verbose_name='Source(Operation wealth creation, etc)'),
        ),
    ]
