# Generated by Django 2.2.16 on 2020-10-26 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20201023_1132'),
        ('farm', '0013_enterprise_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100, null=True)),
                ('benefits', models.CharField(blank=True, max_length=100, null=True)),
                ('what_you_need_to_know', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='enterpriseselection',
            name='recommendation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Ecological_Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_crops_per_ecological_zone', models.CharField(blank=True, max_length=15, null=True)),
                ('crops', models.ManyToManyField(related_name='ecological_zone_crops', to='farm.Crop')),
                ('ecological_zone_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='common.Region')),
            ],
        ),
    ]
