# Generated by Django 2.2.16 on 2020-10-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_ecological_zones_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecological_zones',
            name='zone',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='common.Region'),
        ),
    ]
