# Generated by Django 2.2.16 on 2020-10-25 08:00

from django.db import migrations, models
import django.db.models.deletion
import django_postgres_extensions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_ecological_zones'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='ecological_zones',
        #     name='zone',
        # ),
        migrations.AddField(
            model_name='enterpriseselection',
            name='recommendation',
            field=models.CharField(max_length=100, null=True),
        ),
        # migrations.AlterField(
        #     model_name='ecological_zones',
        #     name='ecological_zone_name',
        #     field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='common.Region'),
        # ),
        migrations.AlterField(
            model_name='ecological_zones',
            name='list_of_crops_per_ecological_zone',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True,  null=True, size=None),
        ),
    ]
