# Generated by Django 2.2.16 on 2020-10-08 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_auto_20201007_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='sector',
        ),
        migrations.CreateModel(
            name='EnterpriseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Sector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enterprise',
            name='enterprise_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.EnterpriseType'),
        ),
    ]
