# Generated by Django 2.2.16 on 2020-10-08 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_auto_20201008_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='expected_profit',
            new_name='capital_invested',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='from_period',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='return_on_investment',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True, verbose_name='Expected Return on Investment'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Sector'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='to_period',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Farm Start Date'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='status',
            field=models.CharField(choices=[(None, '--please select--'), ('open', 'Open'), ('closed', 'Closed')], default='active', max_length=20, verbose_name='Enterprise Status'),
        ),
    ]
