# Generated by Django 2.2.16 on 2020-10-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_auto_20201025_0800'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='ecological_zones',
        #     name='zone',
        # ),
        # migrations.AlterField(
        #     model_name='ecological_zones',
        #     name='ecological_zone_name',
        #     field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='common.Region'),
        # ),
        migrations.AlterField(
            model_name='ecological_zones',
            name='list_of_crops_per_ecological_zone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseselection',
            name='recommendation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
