# Generated by Django 2.2.16 on 2020-10-25 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_auto_20201025_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100, null=True)),
                ('benefits', models.CharField(blank=True, max_length=100, null=True)),
                ('what_you_need_to_know', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='ecological_zones',
        #     name='zone',
        # ),
        # migrations.AlterField(
        #     model_name='ecological_zones',
        #     name='ecological_zone_name',
        #     field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='common.Region'),
        # ),
        migrations.AddField(
            model_name='ecological_zones',
            name='crops',
            field=models.ManyToManyField(related_name='ecological_zone_crops', to='farm.Crop'),
        ),
    ]
