# Generated by Django 2.2.16 on 2020-10-27 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20201023_1132'),
        ('farm', '0015_auto_20201026_0932'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Ecological_Zones',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('list_of_crops_per_ecological_zone', models.CharField(blank=True, max_length=15, null=True)),
        #         ('crops', models.ManyToManyField(related_name='ecological_zone_crops', to='farm.Crop')),
        #         ('ecological_zone_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='common.Region')),
        #     ],
        # ),
        # migrations.AlterField(
        #     model_name='enterpriseselection',
        #     name='recommendation',
        #     field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='farm.Ecological_Zones'),
        # ),
    ]
