# Generated by Django 2.2.16 on 2020-10-27 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20201023_1132'),
        ('farm', '0016_auto_20201027_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecological_Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crops', models.ManyToManyField(related_name='ecological_zone_crops', to='farm.Crop')),
                ('ecological_zone_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='common.Region')),
            ],
        ),
        migrations.AlterField(
            model_name='enterpriseselection',
            name='recommendation',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='farm.Ecological_Zones'),
        ),
    ]
