# Generated by Django 2.2.16 on 2020-10-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_enterprise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='enterprise_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Enterprise Name'),
        ),
    ]
