# Generated by Django 2.2.16 on 2020-10-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0018_auto_20201009_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestanddisease',
            name='query_category',
            field=models.CharField(choices=[(None, '--please select--'), ('availabe', 'Available'), ('not_available', 'Not Available')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pestanddisease',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pestanddisease',
            name='reported_by',
            field=models.TextField(null=True),
        ),
    ]
