# Generated by Django 2.2.16 on 2020-10-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0019_auto_20201012_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestanddisease',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='pestanddisease',
            name='reported_by',
        ),
        migrations.AddField(
            model_name='pestanddisease',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pestanddisease',
            name='query_category',
            field=models.CharField(choices=[(None, '--please select--'), ('pest', 'Pest'), ('disease', 'Disease'), ('general_query', 'General Query')], max_length=25, null=True),
        ),
    ]
