# Generated by Django 2.2.16 on 2020-10-12 14:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0020_auto_20201012_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmrecord',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='farmrecord',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='farmrecord',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='farmrecord',
            name='to_time',
        ),
        migrations.AddField(
            model_name='farmrecord',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone number 1'),
        ),
        migrations.AddField(
            model_name='farmrecord',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='farm_records', to='farm.Enterprise'),
        ),
    ]
