# Generated by Django 2.2.16 on 2020-10-13 06:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0021_auto_20201012_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='farmrecord',
            old_name='activity',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='farmrecord',
            name='activity_type',
        ),
        migrations.AlterField(
            model_name='farmrecord',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='farmrecord',
            name='taken_by',
            field=models.CharField(max_length=100, null=True, verbose_name='Taken by'),
        ),
        migrations.AddField(
            model_name='farmrecord',
            name='record_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='farm.RecordType'),
        ),
    ]
