# Generated by Django 2.2.16 on 2020-10-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0022_auto_20201013_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmrecord',
            name='next_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
