# Generated by Django 2.2.16 on 2020-10-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0023_farmrecord_next_activity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmproduce',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='transaction_from',
        ),
        migrations.AddField(
            model_name='farmproduce',
            name='enterprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='farm_produces', to='farm.Enterprise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='enterprise',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='farm_financial_record', to='farm.Enterprise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmrecord',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='amount',
            field=models.FloatField(verbose_name='Amount paid'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='spent_on',
            field=models.CharField(max_length=200, verbose_name='Payment for'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='transaction_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='transaction_to',
            field=models.CharField(max_length=100, verbose_name='Payment To/From'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='transaction_type',
            field=models.CharField(choices=[(None, '--please select--'), ('income', 'Income'), ('expense', 'expense')], max_length=100),
        ),
    ]
