# Generated by Django 2.2.16 on 2020-10-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0024_auto_20201013_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PestAndDisease',
            new_name='Query',
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='means_of_payment',
            field=models.CharField(choices=[(None, '--please select--'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobilemoney', 'Mobile Money'), ('credit_card', 'credit card'), ('others', 'Others')], max_length=20),
        ),
    ]
