# Generated by Django 2.2.16 on 2020-10-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0024_auto_20201013_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_piece_of_land', models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you own a piece of land or you intend to use rented land')),
                ('what_is_your_inspiration_for_considering_in_farming', models.TextField(blank=True, null=True)),
                ('involved_in_anyother_farming_activity', models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=True, verbose_name='Have  you been involved in other farming sectors')),
                ('scale', models.CharField(max_length=100, null=True)),
                ('sector', models.CharField(max_length=100, null=True)),
                ('full_time_devotion', models.BooleanField(choices=[(None, '--please select--'), (True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you want to devote full-time effort to the farm or would you prefer farming to be a part-time activity?')),
                ('time_allocated_to_farming', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='means_of_payment',
            field=models.CharField(choices=[(None, '--please select--'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobilemoney', 'Mobile Money'), ('credit_card', 'credit card'), ('others', 'Others')], max_length=20),
        ),
    ]
