# Generated by Django 2.2.16 on 2020-10-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityweather',
            old_name='general_remarks',
            new_name='description',
        ),
    ]
