# Generated by Django 2.2.16 on 2020-10-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityweather',
            name='location_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
