# Generated by Django 2.2.16 on 2020-10-23 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_profile_phone_2'),
        ('weather', '0002_auto_20201021_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityweather',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='communityweather',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='communityweather',
            name='longitude',
        ),
        migrations.AddField(
            model_name='communityweather',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.County'),
        ),
        migrations.AddField(
            model_name='communityweather',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.District'),
        ),
        migrations.AddField(
            model_name='communityweather',
            name='parish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Parish'),
        ),
        migrations.AddField(
            model_name='communityweather',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Region'),
        ),
        migrations.AddField(
            model_name='communityweather',
            name='sub_county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.SubCounty'),
        ),
        migrations.AddField(
            model_name='communityweather',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Village'),
        ),
        migrations.AlterField(
            model_name='communityweather',
            name='weather',
            field=models.CharField(choices=[(None, '--please select--'), ('clear_sky', 'Clear sky'), ('few_clouds', 'Few clouds'), ('scattered_clouds', 'Scattered clouds'), ('broken_clouds', 'Broken clouds'), ('shower_rain', 'Shower rain'), ('rain', 'Rain'), ('thunderstorm', 'Thunderstorm'), ('snow', 'Snow'), ('mist', 'Mist')], max_length=50),
        ),
    ]
